name: Eslint + Prettier + Jest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-pr-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run lint
          npm run test:unit
