name: Eslint + Prettier + Jest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-pr-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: install, lint, test
        run: |
          npm ci
          npm run lint
          npm run test:unit

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
